### ISSUE TITLE
IOPlace generating def with non-existent metal layer, metal16

### ISSUE THREAD

**Issue by Colin-Holehouse** [The-OpenROAD-Project/alpha-release#31]
Running the gcd testcase with release OpenROAD-2019-07-15_20-49 the placement step ends with the message:

ERROR: clk have layer as metal16, but not exists in LEF

This is introduced by ioPlacer - it is first present in 2_2_floorplan_io.def

find results/nangate45/gcd -type f -exec grep -l metal16 {} \;
results/nangate45/gcd/2_2_floorplan_io.def
results/nangate45/gcd/2_3_floorplan_tdms.def
results/nangate45/gcd/2_4_floorplan_macro.def
results/nangate45/gcd/2_5_floorplan_pdn.def
results/nangate45/gcd/2_6_floorplan_tapcell.def
results/nangate45/gcd/2_floorplan.def

It looks like the ioPlacer has put pins on metal15 and metal16, instead of metal5 and metal6

**Comment by tajayi** [comment]
I believe this has been resolved in newer versions of the OpenROAD tools (which includes newer ioPlacer commits). I am able to reproduce this using OpenROAD-2019-07-15_20-25 but not OpenROAD-2019-08-09_16-17

You can find the exact ioPlacer commit version by running `cat $OPENROAD/ioplacer.version`. Make sure it is fairly recent.
