### ISSUE TITLE
Makefile will always append new content to the end of tritonCTS.cfg

### ISSUE THREAD

**Issue by mpfogaca** [The-OpenROAD-Project/alpha-release#34]
Hi, all.

Lines 378-389 of file /flow/Makefile will always append new content to the of tritonCTS.cfg, which can lead to bugs.

I suggest changing ">>" of line 378 to ">". This should fix the issue.

Thanks,
--Mateus

**Comment by tajayi** [comment]
Updated in commit 7c0421f6a4cb7f9c5df2fee126b2d40ed72d3d95
