### ISSUE TITLE
Docker build issues

### ISSUE THREAD

**Issue by ahmed-agiza** [The-OpenROAD-Project/alpha-release#38]
I was building the full release, but I found few issues in the docker files for few tools:
1) fastroute/Dockerfile: `RUN git clone https://github.com/The-OpenROAD-Project/FastRoute4-lefdef.git`: need to add **--recursive**

2) ioplacer/Dockerfile: 
   a) `RUN git clone --recursive https://github.com/The-OpenROAD-Project/ioPlacer.git`: need to add **--recursive** too
   b) Need to add `RUN yum install -y zlib-devel` before the cmake execution.

3) For the make build-final command:
I believe: 
`          VERSION=$(subst .tar.gz,,$(subst export/OpenROAD-,,$(wildcard export/OpenROAD-*.tar.gz))); \
         docker build $(DOCKER_BUILD_OPTS) --build-arg VERSION=$$VERSION -t openroad/alpha-release:$$VERSION ./export | tee logs/docker/$*.build.txt
         docker tag openroad/alpha-release openroad/alpha-release:latest
          VERSION=$(subst .tar.gz,,$(subst export/OpenROAD-,,$(wildcard export/OpenROAD-*.tar.gz))); \
         docker build $(DOCKER_BUILD_OPTS) --build-arg VERSION=$$VERSION -t openroad/alpha-release:$$VERSION ./export | tee logs/docker/$*.build.txt
         docker tag openroad/alpha-release openroad/alpha-release:latest
` 
Needs to change:
`
          VERSION=$(subst .tar.gz,,$(subst export/OpenROAD-,,$(wildcard export/OpenROAD-*.tar.gz))); \
         docker build $(DOCKER_BUILD_OPTS) --build-arg VERSION=$$VERSION -t openroad/alpha-release:$$VERSION ./export | tee logs/docker/$*.build.txt; \
         docker tag openroad/alpha-release:$$VERSION openroad/alpha-release:latest
`  (add $$VERSION to the docker tag & make sure $$VERSION value is available by stitiching all the commands with ;)

**Comment by tajayi** [comment]
Hi @ahmed-agiza 
Thanks for spotting those issues. I believe the first two should be resolved by 08e1e1ba15a68f376d46648813a5510128212a6c and the last by 28803eae54c6fbce2d6e21c1323e43ef3208de2f

Thanks
