### ISSUE TITLE
Need additional prerequisites for python

### ISSUE THREAD

**Issue by RTimothyEdwards** [The-OpenROAD-Project/alpha-release#4]
Please note that the install instructions should indicate that it is necessary to install the following packages for python:

queuelib
matplotlib

Install with pip3, e.g.:

pip3 install queuelib
pip3 install matplotlib

Note that the script "runTritonCTS.tcl" makes references to "exec python", which is python2 on most (all?) systems.  The dependency list indicates python3.  To make it work correctly, I had to change all occurrences of "python" in that script to "python3".

**Comment by tajayi** [comment]
Hi Tim,
I have updated the readme withe python packages required. I have also filed an issue (https://github.com/The-OpenROAD-Project/TritonCTS/issues/15) with the appropriate repository. I'll close this issue here and track the script changes there.

Thanks
