### ISSUE TITLE
Add the LowRISC Ibex SoC as test bench

### ISSUE THREAD

**Issue by mithro** [The-OpenROAD-Project/alpha-release#7]
It would be good to add the LowRISC Ibex core + SoC as a test bench. You can find it at https://github.com/lowRISC/ibex

> This core was initially developed as part of the PULP platform under the name "Zero-riscy" [1], and has been contributed to lowRISC who maintains it and develops it further. It is under active development, with further code cleanups, feature additions, and test and verification planned for the future.

![image](https://user-images.githubusercontent.com/21212/61399204-a4375e00-a89b-11e9-9c03-7692e1620d9f.png)

The core has been taped out multiple times and will have a strong focus on adding and improving security -- hence they care deeply about transparency and reproducibility. It would be an awesome fit for an open source toolchain!

**Comment by tajayi** [comment]
Ibex has been added and is now running through the flow as of the latest commit. There are about 8 DRCs on nangate45 and about 7 DRCs on tsmc65lp. We'll continue working (on a broader scope) to get lvs clean consistently across all designs

**Comment by mithro** [comment]
Great work!

How do I replicate your results?

**Comment by tajayi** [comment]
You should be able to run it on the Nangate45 platform.
Follow the instructions on the flow page: https://github.com/The-OpenROAD-Project/alpha-release/tree/master/flow (Let me know if it needs more work)

Once the flow is setup (you may want to run the default small design to validate your isntalld), open the Makefile in the `flow` folder and uncomment ibex_tsmc65lp to set it as the design. Run `make`
